config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'categories#index'

  resources 'categories' do
  	resources 'projects' do
      resources 'comments'
    end
  end

  resources 'posts'
  resources 'references'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :projects
	validates :name, :presence => true
	validates :description, :presence => true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	validates :body, :presence => true
	belongs_to :project
	belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, :presence => true
  validates :body, :presence => true
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :category
	has_many :comments
	validates :name, :presence => true
	validates :description, :presence => true
	validates :link, :presence => true
end

app/models/reference.rb
class Reference < ActiveRecord::Base
	validates :body, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def is_admin?
   return current_user && current_user.admin?
  end

  helper_method :is_admin?

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	before_filter :authenticate_user!, except: [:index, :show]

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)
		if @category.save
			redirect_to categories_path
		else
			render :new
		end
	end

	def show
		@category = Category.find(params[:id])
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])
		if @category.update(category_params)
			redirect_to category_path(@category)
		else
			render :edit
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy
		redirect_to categories_path
	end

	private
	def category_params
		params.require(:category).permit(:name, :description)
	end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @user = current_user
    @category = Category.find(params[:project_id])
    @project = Project.find(params[:project_id])
    @comment = Comment.new
    respond_to do |format|
      format.html { redirect_to category_project_path(@category, @project) }
      format.js
    end
  end

  def create
    @user = current_user
    @category = Category.find(params[:project_id])
    @project = Project.find(params[:project_id])
    @comment = @project.comments.new(comment_params)
    @user.comments.push(@comment)
    if @comment.save
      redirect_to category_project_path(@category, @project)
    else
      render :new
    end
  end

  private
	def comment_params
		params.require(:comment).permit(:body)
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new
    end
  end

  def post_params
		params.require(:post).permit(:title, :body)
	end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_filter :authenticate_user!, except: [:show]

	def new
		@category = Category.find(params[:category_id])
		@project = @category.projects.new
	end

	def create
		@category = Category.find(params[:category_id])
		@project = @category.projects.new(project_params)
		if @project.save
			redirect_to category_path(@project.category)
		else
			render :new
		end
	end

	def edit
		@category = Category.find(params[:category_id])
		@project = @category.projects.find(params[:id])
	end

	def update
		@category = Category.find(params[:category_id])
		@project = @category.projects.find(params[:id])
		# binding.pry
		if @project.update(project_params)
			redirect_to category_project_path(@category, @project)
		else
			render :edit
		end
	end

	def show
		@category = Category.find(params[:category_id])
		@project = @category.projects.find(params[:id])
	end

	def destroy
		@category = Category.find(params[:category_id])
		@project = @category.projects.find(params[:id])
		@project.destroy
		redirect_to categories_path(@category)
	end

	private
	def project_params
		params.require(:project).permit(:name, :description, :link)
	end

end

app/controllers/references_controller.rb
class ReferencesController < ApplicationController

  def index
    @references = Reference.all
    respond_to do |format|
      format.html { redirect_to references_path }
      format.js
    end
  end

  def create
    @reference = Reference.new(reference_params)
    @reference.save
    @references = Reference.all
    respond_to do |format|
      format.html { redirect_to references_path }
      format.js
    end
  end

  private
	def reference_params
		params.require(:reference).permit(:body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/edit.html.erb
<h2>Edit Category</h2>

<%= render "layouts/category_form", :object => @category %>

<p> <%= link_to 'Back to categories', categories_path %> </p>

app/views/categories/index.html.erb
<h1>Toby Alden</h1>

<p>The personal portfolio of Toby Alden.</p>

<ul>
	<% @categories.each do |category| %>
		<li> <%= link_to category.name, category_path(category) %>  </li>
	<% end %>
</ul>

<% if is_admin? %>
	<p> <%= link_to 'New Category', new_category_path %> </p>
<% end %>

<p> <%= link_to 'Personal Blog', posts_path %> </p>

<p> <%= link_to 'References', references_path, id: 'references-link', remote: true %> </p>

<div id="references-form">

</div>

app/views/categories/new.html.erb
<h2>New Category</h2>

<%= render "layouts/category_form", :object => @category %>

<p> <%= link_to 'Back to categories', categories_path %> </p>

app/views/categories/show.html.erb
<h2> <%= @category.name %> </h2>

<p> <%= @category.description %> </p>

<ul>
	<% @category.projects.each do |project| %>
		<li> <%= link_to project.name, category_project_path(@category, project) %> </li>
	<% end %>
</ul>

<% if is_admin? %>
	<p> <%= link_to 'New Project',  new_category_project_path(@category) %> </p>
	<p> <%= link_to 'Edit Category', edit_category_path(@category) %> </p>
	<p> <%= link_to 'Delete Category', category_path(@category), :method => 'delete' %> </p>
<% end %>

<p> <%= link_to 'Back to categories', categories_path %> </p>

app/views/comments/_comments.html.erb
<h1>New Comment</h1>

<%= form_for [@category, @project, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= form_for [@category, @project, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

app/views/comments/new.js.erb
$('#new-comment-box').html("<%= j render('comments') %>");

app/views/layouts/_category_form.html.erb
<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/layouts/_project_form.html.erb
<%= form_for [@category, @project] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :link %>
  <%= f.text_field :link %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>

  <div id="user_nav">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> |
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>

  <% if flash[:notice] %>
     <div class="alert alert-success" role="alert"> <%= flash[:notice] %> </div>
   <% end %>

   <% if flash[:alert] %>
     <div class="alert alert-danger" role="alert"> <%= flash[:alert] %> </div>
   <% end %>

	<%= yield %>
</div>


</body>
</html>

app/views/posts/index.html.erb
<h1>Blog posts</h1>

<ol>
  <% @posts.each do |post| %>
    <li>
      <strong> <%= post.title %> </strong> <br>
      <%= post.body %>
    </li>
  <% end %>
</ol>

<% if is_admin? %>
	<p> <%= link_to 'New Post', new_post_path %> </p>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h2>Edit Project</h2>

<%= render "layouts/project_form", :object => [@category, @project] %>

app/views/projects/new.html.erb
<h2>New Project</h2>

<%= render "layouts/project_form"%>

app/views/projects/show.html.erb
<h1> <%= @project.name %> </h1>

<p> <%= @project.description %> </p>

<a href="http://www.<%=@project.link%>">Project Homepage</a>

<% if is_admin? %>
  <p> <%= link_to 'Edit Project', edit_category_project_path(@category, @project) %> </p>
  <p> <%= link_to 'Delete Project', category_project_path(@category, @project), :method => 'delete' %> </p>
<% end %>

<h4>Comments:</h4>
<ul>
  <% @project.comments.each do |comment| %>
    <li> <strong> <%= comment.user.email %>: </strong> <%= comment.body %> </li>
  <% end %>
</ul>

<p> <%= link_to 'New Comment', new_category_project_comment_path(@category, @project), remote: true %> </p>

<div id="new-comment-box">

</div>

<p> <%= link_to 'Back to ' + @category.name, category_path(@category) %> </p>

app/views/references/_references.html.erb
<ul>
  <% @references.each do |reference| %>
    <li> <%= reference.body %> </li>
  <% end %>
</ul>

<%= form_for Reference.new, remote: true do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <%= f.submit %>
<% end %>

<%= link_to 'Hide References', root_path %>

app/views/references/create.js.erb
$('#references-form').html("<%= j render('references') %>");

app/views/references/index.js.erb
$('#references-link').hide().after("<%= j render('references') %>");